version: "3.8"

services:
  server:
    image: sweetbubalexxx/moneyger-notifications:v1.0.0
    command: gunicorn -c gunicorn.conf.py 'app.application:create_app()'
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      default:
      service_public_network:
        aliases:
          - notifications_service
    env_file: .env
    environment:
      DATABASE_URL: mongodb://db:27017?authSource=admin
      DATABASE_USER: ${DATABASE_USER:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      CACHE_URL: redis://:${REDIS_PASSWORD:?}@redis:6379/0
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD:?}@redis:6379/1
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD:?}@redis:6379/2
      XFF_TRUSTED_PROXY_DEPTH: ${XFF_TRUSTED_PROXY_DEPTH:-1}

  mq_consumer:
    extends:
      service: server
    depends_on:
      - db
      - redis
    command: python ./start_consumers.py

  celery_worker:
    extends:
      service: server
    depends_on:
      - db
      - redis
    command: celery -A app.celery.entrypoint worker --autoscale 2,1 --loglevel INFO --events

  celery_beat:
    extends:
      service: server
    depends_on:
      - db
      - redis
    command: celery -A app.celery.entrypoint beat -s /var/lib/celery/celerybeat-schedule --loglevel INFO
    volumes:
      - celery_beat_data:/var/lib/celery

  db:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER:?}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD:?}
      MONGODB_DATA_DIR: /data/db
    volumes:
      - database_data:/data/db
    expose:
      - 27017

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel notice --requirepass ${REDIS_PASSWORD:?}
    restart: unless-stopped
    expose:
      - 6379

volumes:
  database_data:
  celery_beat_data:

networks:
  service_public_network:
    name: ${SERVICE_NETWORK:-moneyger-notifications}
    external: ${SERVICE_NETWORK_EXTERNAL:-false}
