version: "3.8"

services:
  db:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER:?}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD:?}
      MONGODB_DATA_DIR: /data/db
    expose:
      - 27017
    volumes:
      - database_data:/data/db

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel notice --requirepass ${REDIS_PASSWORD:?}
    restart: unless-stopped
    expose:
      - 6379

volumes:
  database_data:
