version: "3.8"

services:
  server:
    extends:
      file: docker-compose.yml
      service: server
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: poetry run flask --app app.application run -h 0.0.0.0 -p 80
    restart: "no"
    volumes:
      - ./:/app:ro
    ports:
      - "${PORT:-80}:80"

  mq_consumer:
    extends:
      service: server
    command: poetry run python ./start_consumers.py
    ports: []

  db:
    extends:
      file: docker-compose.yml
      service: db
    restart: "no"
    ports:
      - "27017:27017"

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    command: redis-server --loglevel debug --requirepass ${REDIS_PASSWORD:?}
    restart: "no"
    ports:
      - "6379:6379"

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  database_data:
  rabbitmq_data:
